### ISSUE TITLE
Stuck Loading On Nuxt

### ISSUE THREAD

**Issue by BlackDahlia313** [stemplayer-js/stemplayer-js#2]
Trying to integrate this into my vue/nuxt project and was able to get it in as a plugin.

But not matter what m3u8 playlists I try, its just spinning.

![image](https://github.com/stemplayer-js/stemplayer-js/assets/44903742/746987cb-e5bd-49ca-819e-9dc85d2591c9)

No errors that I am seeing preventing it from playing. I also do see the response in the network tab loading the .m3u8

Any idea?

**Comment by BlackDahlia313** [comment]
I believe it has to do with the sample rate.

I am testing with BunnyCDN. So im sure the sample rate would stay the same between encoding.

**Comment by BlackDahlia313** [comment]
I copied your demo html into the page it loaded fine. It seems I must have waveforms generated. Ill further test that.

**Comment by mpcremer** [comment]
Hi!

Thanks for adding a link to your audio. That's helpful.

Your m3u8 contains an index to further nested m3u8 files (e.g. `640x360/video.m3u8`) which file then contains ts (`video*.ts`) files. I'm afraid this nested structure cannot be consumed by the Stem Player.

However, I hope that [this](https://github.com/sound-ws/docker-segment-audio) may help you generate audio in a format that can be played back.

The result should look something like [this](https://github.com/stemplayer-js/stemplayer-js/blob/main/assets/audio/106%20BELL_05.3.m3u8)

Hope that helps...

**Comment by BlackDahlia313** [comment]
https://d178eqdhz8mr00.cloudfront.net/testsong/plumb.m3u8
https://d178eqdhz8mr00.cloudfront.net/testsong/plumbtest.m3u8

The player doesn't spin forever on load, but it doesnt play the file. I can see the correct time loaded, but it spins after hitting play.

**Comment by BlackDahlia313** [comment]
I see.. yours references .mp3 instead of .ts

**Comment by BlackDahlia313** [comment]
Tried with mp3 and same thing at least for myself.

`<soundws-stem label="Guitar A" src="https://d178eqdhz8mr00.cloudfront.net/testsong/finaltest/file.m3u8" waveform="https://d178eqdhz8mr00.cloudfront.net/testsong/maintest.json"></soundws-stem>`

**Comment by BlackDahlia313** [comment]
Deploying this now to try instead of manually in elasticoder converting. 

https://github.com/stemplayer-js/api

**Comment by mpcremer** [comment]
Cool.. 

I'll send an invite through slack so we can assist

**Comment by mpcremer** [comment]
For reference, you can try this to decode audio: https://github.com/stemplayer-js/docker-process-audio

And this to generate waveforms: https://github.com/stemplayer-js/docker-generate-waveforms
