### ISSUE TITLE
Solo boolean not working

### ISSUE THREAD

**Issue by BlackDahlia313** [stemplayer-js/stemplayer-js#3]
Hey!

Attempting to set solo for certain stems via stem property and the boolean is not affecting anything.

I have to use muted as a workaround atm.

**Comment by mpcremer** [comment]
Hey!

Yes, thanks for pointing it out. Try [3.2.0](https://www.npmjs.com/package/@stemplayer-js/stemplayer-js/v/3.2.0)

Setting solo to `true` should now cause the state on the other stems to be changed too. Setting to `false` should "un-solo"

Hope that helps...

**Comment by BlackDahlia313** [comment]
Will give this a try asap! Thank you!

**Comment by BlackDahlia313** [comment]
@mpcremer Hey! Working now ty! Same question about loop.

**Comment by mpcremer** [comment]
Great.. I created a separate issue for loop.
