### ISSUE TITLE
Using the library with React (Typescript)

### ISSUE THREAD

**Issue by UknownGino** [stemplayer-js/stemplayer-js#7]
Hi, is there any way to use the library with React? 
Right now I've imported the library with `import '@stemplayer-js/stemplayer-js/stemplayer.js';` but I'm unable to use any component.

**Comment by mpcremer** [comment]
Hi, Thanks for pointing this out. 

Stemplayer-js is a web-component built with Lit: Try https://lit.dev/docs/frameworks/react/

When we have the time we'll create a react wrapper component to make this easier. 

Hope that works...

**Comment by UknownGino** [comment]
I'll give that a shot, thank you!
I have another question, is there any way to use this only as a "backend"? Like not showing (and not hiding via CSS with something like `display: none;`) any user interface at all?

**Comment by mpcremer** [comment]
Hi... yes the stemplayer is just a (custom) html element. So you would protect it the same way you would protect any other admin part of a user interface... e.g. by making sure the UI is only rendered when logged in + ensuring any HTTP requests to audio assets are protected by a valid session, or JWT or some other form of authentication.

**Comment by mpcremer** [comment]
ah.. I understand. In that case perhaps you can best use https://github.com/sound-ws/hls-web-audio

which is the library which we created for controlling the audio playback and is used by stemplayer-js...

**Comment by UknownGino** [comment]
Thank you so much!
